function $NOP(){}function $I(b){return document.getElementById(b)}function $T(b,d){return(d||document).getElementsByTagName(b)}function $S(b,d){return(d||document).querySelector(b)}function $A(b,d){return(d||document).querySelectorAll(b)}function $explict(b,d){window[b]=d}
function $extend(b,d,c,f){if(c)if(f)(function g(a,b){for(var c in b)a[c]instanceof Object&&g(a[c],b[c])})(b,d);else for(var a in d)b[a]=d[a];else if(f)(function(a,b){for(var c in b)c in a||a[c]instanceof Object&&rdext(a[c],b[c])})(b,d);else for(a in d)a in b||(b[a]=d[a])}
function $define(b,d){var c=/^(set|get)([A-Z])(.*)/,f={},a;for(a in d){var e=c.exec(a),g=d[a];Object.defineProperty(b,a,{value:g,writeable:!0});if(e){if("set"===e[1]){if(1!==g.length)continue}else if(0!==g.length)continue;var h=e[2].toLowerCase()+e[3];f.hasOwnProperty(h)||(f[h]={});f[h][e[1]]=g}}Object.defineProperties(b,f)}function $declare(b,d){b.prototype.constructor=b;$define(b.prototype,d)}function $inherit(b,d,c){b.prototype={constructor:b,__proto__:d.prototype};c&&$define(b.prototype,c)}
function $prefix(b,d){var c={},f;for(f in b)c[d+f]=b[f];return c}function $clone(b){var d={},c;for(c in b)d[c]=b[c];return d}function $merge(b,d){return $extend($clone(b),d)}function $bind(b,d){var c={},f;for(f in b)c[f]=b[f].bind(d);return c}function $default(b,d){return void 0===b?d:b}function $random(b){return Math.floor(Math.random()*b)}function $printf(b){var d=arguments;return b.replace(/(.)?\$S(\d+)(.)?/g,function(b,f,a,e){return $default(f,"")+d[parseInt(a,10)]+$default(e,"")})}
function $wrap(b,d){if(b.__proto__)b.__proto__=d.prototype;else{var c=d.__default?d.__default():new d;$extend(c,b);b=c}d.__wrap&&d.__wrap(b);return b}
(function(){function b(a){return"data-"+a.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}function d(a,e,g,b,c){var d=new XMLHttpRequest;d.onload=function(a){a=null;try{a=JSON.parse(d.responseText)}catch(e){c(e,null)}2===~~(d.status/100)?b?c(null,$wrap(a,b)):c(null,a):401===d.status?(console.error(401,a),location.href="https://sso.stu.edu.cn/login?service="+encodeURIComponent(location.href)):c(d.status,a)};d.onerror=function(a){console.error(a);c(a)};d.open(a,e,!0);d.setRequestHeader("Accept",
"application/json");"get"!==a.toLowerCase()?(g=JSON.stringify(g),d.setRequestHeader("Content-Type","application/json"),d.send(g)):d.send(null)}function c(a,e,g){this.node=a;this.begins=[];this.targets=[];this.fields=[];this.mapping=[];this.singleton=g;for(var b=0;b<e.length;b++){var c=e[b]instanceof Array?e[b]:[e[b]];this.begins.push(this.targets.length);for(var d=0;d<c.length;d++){var f=this.parse(a,c[d]);f&&(this.targets.push(c[d]),this.fields.push(f),this.mapping.push(b))}}this.begins.push(this.targets.length);
g||a.dispose()}var f={};$explict("$E",function(a,e){for(var b=f.hasOwnProperty(a)?f[a].cloneNode(!0):document.createElement(a),c=1;c<arguments.length;c++)if(arguments[c]instanceof HTMLElement)b.appendChild(arguments[c]);else if("string"===typeof arguments[c])b.appendChild(document.createTextNode(arguments[c]));else for(var d in arguments[c])"class"!==d?b.setAttribute(d,arguments[c][d]):b.className=arguments[c][d];return b});$define(String.prototype,{repeat:function(a){for(var e="",b=0;b<a;b++)e+=
this;return e},paddingLeft:function(a,e){return this.length<e?a.repeat(e-this.length)+this:this},paddingRight:function(a,e){return this.length<e?this+a.repeat(e-this.length):this}});$define(Number.prototype,{clamp:function(a,e){var b=Math.max(this,a);return void 0!==e?Math.min(b,e):b}});$define(Array.prototype,{min:function(){for(var a=this[0],e=1;e<this.length;e++)this[e]<a&&(a=this[e]);return a},max:function(){for(var a=this[0],e=1;e<this.length;e++)this[e]>a&&(a=this[e]);return a},add:function(a){return-1===
this.indexOf(a)?this.push(a):-1},remove:function(a){var e=this.indexOf(a);if(-1===e)return null;for(;e<this.length-1;e++)this[e]=this[e+1];this.pop();return a},rotate:function(a){for(;0<a--;)this.unshift(this.pop());return this}});void 0===Array.map&&"forEach every some filter map reduce reduceRight".split(" ").forEach(function(a){var e=Array.prototype[a];Object.defineProperty(Array,a,{value:function(a,b,c){return e.call(a,b,c)}})});$define(Element.prototype,{setClass:function(a,e){return e?this.addClass(a):
this.removeClass(a)},hide:function(){return this.addClass("HIDE")},show:function(){return this.removeClass("HIDE")},getSize:function(){return{w:this.offsetWidth,h:this.offsetHeight}},getPos:function(){for(var a=this,e=0,b=0;a.offsetParent;)e+=a.offsetLeft,b+=a.offsetTop,a=a.offsetParent;return{x:e,y:b}},getScreenPos:function(){var a=this.getPos();a.x-=$DE.scrollLeft;a.y-=$DE.scrollTop;return a},setPos:function(a){"x"in a&&(this.style.left=a.x+"px");"y"in a&&(this.style.top=a.y+"px");return this},
setSize:function(a){"w"in a&&(this.style.width=a.w+"px");"h"in a&&(this.style.height=a.h+"px");return this},measure:function(){this.parentNode||document.body.appendChild(this);return this.addClass("MEASURING").getSize()},unmeasure:function(){var a=this;setTimeout(function(){a.removeClass("MEASURING")},0);return this},dispose:function(){return this.parentNode.removeChild(this)}});$define(Element.prototype,document.documentElement.classList?{addClass:function(a){this.classList.add(a);return this},removeClass:function(a){this.classList.remove(a);
return this},hasClass:function(a){return this.classList.contains(a)},toggleClass:function(a){this.classList.toggle(a);return this}}:{addClass:function(a){this.hasClass(a)||(this.className+=" "+a);return this},removeClass:function(a){this.className=this.className.replace(RegExp("\\s*\\b"+a+"\\b","g"),"");return this},hasClass:function(a){return RegExp("\\b"+a+"\\b").test(this.className)},toggleClass:function(a){return this.hasClass(a)?this.removeClass(a):this.addClass(a)}});$define(Element.prototype,
document.documentElement.dataset?{setData:function(a,e){this.dataset[a]=e;return this},getData:function(a){return this.dataset[a]},unsetData:function(a){delete this.dataset[a];return this}}:{setData:function(a,e){this.setAttribute(b(a),e);return this},getData:function(a){return this.getAttribute(b(a))},unsetData:function(a){this.removeAttribute(b(a));return this}});$define(Node.prototype,{ancestorOf:function(a,e){for(a=e?this.parentNode:a;a;a=a.parentNode)if(this===a)return!0;return!1},findAncestorOfType:function(a,
e){for(var b=e?this.parentNode:this;b&&b!==document;b=b.parentNode)if(b.getAttribute("data-type")===Type.__type)return b;return null},findTypedAncestor:function(a){for(a=a?this.parentNode:this;a&&a!==document;a=a.parentNode)if(void 0!==a.getAttribute("data-type"))return a;return null},findAncestorOfTagName:function(a,b){for(var c=b?this.parentNode:this;c&&c!==document;c=c.parentNode)if(c.tagName===a)return c;return null},findAncestorHasAttribute:function(a,b){for(var c=b?this.parentNode:this;c&&c!==
document;c=c.parentNode)if(c.hasAttribute(a))return c;return null},clear:function(){for(;this.firstChild;)this.removeChild(this.firstChild);return this},setFirstTextNodeValue:function(a){for(var b=this.firstChild;b;b=b.nextChild)if(3===b.nodeType)return b.nodeValue=a,this;this.appendChild(document.createTextNode(a));return this}});["get","post","put","del"].forEach(function(a){d[a]=d.bind(d,"del"==a?"delete":a)});$explict("Request",d);$declare(c,{generate:function(a){for(var b=0;b<this.fields.length;b++)this.fields[b].nodeValue=
$default(a[this.mapping[b]],"");return this.singleton?this.node:this.node.cloneNode(!0)},parse:function(a,b){b=b.split("@");var c="."===b[0]?a:$S(b[0],a);if(b[1]){var d=c.getAttributeNode(b[1]);d||(d=document.createAttribute(b[1]),c.setAttributeNode(d));c=d}c instanceof HTMLElement&&2!==c.nodeType&&3!==c.nodeType&&(c=c.firstChild&&3===c.firstChild.nodeType?c.firstChild:c.appendChild(document.createTextNode("")));return c}});$explict("Tmpl",c);$define(CSSStyleSheet.prototype,{empty:function(){return 0===
this.cssRules.length},clear:function(){for(this.disabled=!0;0<this.cssRules.length;)this.deleteRule(0);this.disabled=!1},setRules:function(a){this.disabled=!0;for(var b=0;b<a.length;b++)this.appendRule(a[b]);this.disabled=!1},appendRule:function(a,b){var c=this.cssRules.length;this.insertRule?this.insertRule(a+"{}",c):this.addRule(a,";");c=this.cssRules[c];if(b)for(var d in b)c.style[d]=b[d];return c}});$explict("StyleSheet",function(){document.head.appendChild(document.createElement("style")).type=
"text/css";return document.styleSheets[document.styleSheets.length-1]})})();
(function(){var b={},d=!1;$define(Element.prototype,{getInstance:function(){var b=this.findTypedAncestor();if(b){var d=b.getInstanceType();if(d&&d._&&void 0!==b.getData("id"))return d._(b.getData("id"))}},setInstanceType:function(b,d){this.setData("type",b.__type);void 0!==d&&this.setData("id",d);return this},getInstanceType:function(){var c=this.findTypedAncestor();if(c&&(c=c.getData("type"))&&b[c])return b[c]}});$extend(Element.prototype,{dispose:function(){var b=this.getInstance();b&&b.dispose&&
b.dispose();return this.parentNode.removeChild(this)}},!0);window.addEventListener("DOMContentLoaded",function(){var c=document.body.getData("loadModule"),f;for(f in b){var a=b[f];a.init&&a.init();f===c&&a.pageLoad&&a.pageLoad()}["click","dblclick"].forEach(function(a){document.addEventListener(a,function(c){for(var d=c.target.findTypedAncestor();d;d=d.findTypedAncestor(!0)){c.node=d;var f=d.getData("type");if(b.hasOwnProperty(f)){f=b[f];if(f._&&void 0!==d.getData("id")){var k=f._(d.getData("id"));
if(!k)continue;if(k[a]){if(k[a](c))continue;return!1}}if(f[a]){if(f[a](c))continue;return!1}if(f.eventHandler)return f.eventHandler(a,c)}}},!1)});d=!0},!1);$explict("Dispatcher",{register:function(c){b[c.__type]=c;console.log(c.__type,d);d&&c.init&&c.init()},unregister:function(c){delete b[c.__type]},fire:function(c,d){for(var a in b){var e=b[a];if(e[c])e[c](d)}}})})();